[package]
name = "package_checker"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
regex = "1.10"
serde_json = "1.0"
walkdir = "2.5"
rayon = "1.10"
csv = "1.3"
num_cpus = "1.16"